name: OCDFlash
description: 'Flash a board using OpenOCD'
inputs:
  boards:
    description: 'ID of the board to flash'
    required: true
  project:
    description: 'Name of the project to flash'
    required: true
  msdk_path:
    description: 'Path to root of MSDK'
    required: false
    default: '.'
  build:
    description: 'Build before flashing?'
    required: false
    default: 'true'
  build_flags:
    description: 'Additional build flags.'
    required: false
    default: ''
  distclean:
    description: 'Perform distclean before building? (ignored if build=false)'
    required: false
    default: 'false'
  owner:
    description: "Name of owner of resources"
    required: false
  suppress_output:
    description: 'Used to suppress console unless an error is encountered.'
    required: false
    default: 'true'
runs:
  using: 'node20'
  main: 'index.js'
