name: makeProject
description: 'Build a project with make'
inputs:
  path:
    description: 'Path to the project'
    required: false
    default: '.'
  distclean:
    description: 'Perform distclean before building?'
    required: false
    default: 'false'
  build_flags:
    description: 'Additional build flags.'
    required: false
    default: ''
  suppress_output:
    description: 'Used to suppress console unless an error is encountered.'
    required: false
    default: 'false'
runs:
  using: 'node20'
  main: 'index.js'
