name: OCDErase
description: 'Mass erase a board using OpenOCD'
inputs:
  board:
    description: 'ID of the board to erase'
    required: true
  suppress_output:
    description: 'Used to suppress console unless an error is encountered.'
    required: false
    default: 'false'
runs:
  using: 'node20'
  main: 'index.js'
