name: 'DATSC-TEST'
description: 'DATSC Test Action'
inputs:
  board_client:
    description: 'Board for client'
    required: true
  board_server:
    description: 'Board for server'
    required: true
  msdk_path:
    description: "Path to root of MSDK"
    required: false
    default: '.'
runs:
  using: 'shell'
  main: ./run.sh
